# Generated by Django 5.0.3 on 2024-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=100)),
                ('sumber', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=100)),
                ('sumber', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
            ],
        ),
    ]
